export const offersData = [
    {
      id: 1,
      img: "/offer1.png",
      gift: "/cola.png",
      giftLabel: "+ Free Cola",
      title: "Pepperoni Pizza",
      desc: "Spicy pepperoni with mozzarella & tomato sauce. Made with fresh ingredients and baked to perfection.",
      price: 199,
      oldPrice: 249,
      discount: "20% OFF",
      discountPercentage: 20,
      category: "Pizza",
      ingredients: ["Pepperoni", "Mozzarella", "Tomato Sauce", "Oregano"],
      preparationTime: "30-45 min",
      calories: "850 kcal",
    },
    {
      id: 2,
      img: "/offer2.png",
      gift: "/fries.png",
      giftLabel: "+ Free Fries",
      title: "Veggie Mix",
      desc: "Fresh mushrooms, olives, peppers & cheese. A healthy and delicious option for veggie lovers.",
      price: 169,
      oldPrice: 199,
      discount: "15% OFF",
      discountPercentage: 15,
      category: "Pizza",
      ingredients: ["Mushrooms", "Olives", "Bell Peppers", "Onions", "Mozzarella"],
      preparationTime: "30-45 min",
      calories: "720 kcal",
    },
    {
      id: 3,
      img: "/offer3.png",
      gift: "/cola.png", // changed from duplicate image
      giftLabel: "+ Extra Small Pizza",
      title: "Cheese Lovers",
      desc: "Parmesan, cheddar & mozzarella blend. A triple cheese delight for cheese enthusiasts.",
      price: 149,
      oldPrice: 199,
      discount: "25% OFF",
      discountPercentage: 25,
      category: "Pizza",
      ingredients: ["Parmesan", "Cheddar", "Mozzarella", "Garlic"],
      preparationTime: "30-45 min",
      calories: "980 kcal",
    },
    {
      id: 4,
      img: "/offer4.png",
      gift: null,
      giftLabel: null,
      title: "BBQ Chicken",
      desc: "Smoky BBQ sauce with tender chicken, red onions, and cilantro. A perfect blend of sweet and savory.",
      price: 179,
      oldPrice: 259,
      discount: "30% OFF",
      discountPercentage: 30,
      category: "Pizza",
      ingredients: ["Chicken", "BBQ Sauce", "Red Onions", "Cilantro", "Mozzarella"],
      preparationTime: "30-45 min",
      calories: "890 kcal",
    },
  ];