import "./globals.css";
import ToastProvider from "./Components/ToastProvider";
import MenuProvider from "./Context/MenuContext";
import {CartProvider} from './Context/CartContext'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <div>

          <MenuProvider> <CartProvider>{children}</CartProvider></MenuProvider>
          <ToastProvider position="bottom-right" />
        </div>
      </body>
    </html>
  );
}
